<!DOCTYPE html>
<html xmlns:ftl="http://www.w3.org/1999/xhtml">
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Car buy</title>
</head>
<body>
<h1>Welcome to Car buying site</h1>

<nav>
    <form action="/user/add" method="get" style="display:inline;">
        <button type="submit">Add User</button>
    </form>

    <form action="/car/add" method="get" style="display:inline;">
        <button type="submit">Add Car</button>
    </form>

</nav>
</body>
</html>
